<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.9.9 on win32)" generated="20240719 22:32:43.904" rpa="false" schemaversion="3">
<suite id="s1" name="DDT2" source="d:\QA et Automatisation\Testing Auto\robotFramework\RobotFramework_Tutorial\Resources\DDT2.robot">
<kw name="Opening my browser" library="Resources" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${url}</arg>
<arg>${Browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20240719 22:32:45.441" level="INFO">Opening browser 'chrome' to base url 'https:/admin-demo.nopcommerce.com/'.</msg>
<msg timestamp="20240719 22:32:46.073" level="WARN">The chromedriver version (125.0.6422.141) detected in PATH at C:\Users\AYMEN\AppData\Local\Programs\Python\Python39\Scripts\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.182 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry</msg>
<status status="PASS" starttime="20240719 22:32:45.441" endtime="20240719 22:32:49.367"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20240719 22:32:49.370" endtime="20240719 22:32:49.503"/>
</kw>
<status status="PASS" starttime="20240719 22:32:45.441" endtime="20240719 22:32:49.509"/>
</kw>
<test id="s1-t1" name="LoginTestUsingExcel" line="10">
<kw name="Invalid Login">
<arg>${username}</arg>
<arg>${password}</arg>
<msg timestamp="20240719 22:32:49.534" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20240719 22:32:49.532" endtime="20240719 22:32:49.547"/>
</kw>
<status status="FAIL" starttime="20240719 22:32:49.513" endtime="20240719 22:32:49.566">Variable '${username}' not found.</status>
</test>
<kw name="closing my browsers" library="Resources" type="TEARDOWN">
<kw name="Close All Browsers" library="SeleniumLibrary">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20240719 22:32:49.573" endtime="20240719 22:32:57.129"/>
</kw>
<status status="PASS" starttime="20240719 22:32:49.572" endtime="20240719 22:32:57.131"/>
</kw>
<status status="FAIL" starttime="20240719 22:32:43.912" endtime="20240719 22:32:57.133"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="DDT2">DDT2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240719 22:32:45.441" level="ERROR">[ DataDriver ] Error in robot file:
  File "d:\QA et Automatisation\Testing Auto\robotFramework\RobotFramework_Tutorial\Resources\DDT2.robot", line 0</msg>
<msg timestamp="20240719 22:32:45.441" level="ERROR">In source file:
  File "d:\QA et Automatisation\Testing Auto\robotFramework\RobotFramework_Tutorial\Resources\..\Resources\Data.xlsx", line 0</msg>
<msg timestamp="20240719 22:32:45.441" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ImportError: Requirements (pandas, openpyxl) for XLSX support are not installed.
    Use 'pip install -U robotframework-datadriver[XLS]' to install XLSX support.</msg>
<msg timestamp="20240719 22:32:46.073" level="WARN">The chromedriver version (125.0.6422.141) detected in PATH at C:\Users\AYMEN\AppData\Local\Programs\Python\Python39\Scripts\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.182 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry</msg>
</errors>
</robot>
